apiVersion: apps/v1
kind: Deployment
labels:
  app: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
         app: my-deployment
    spec:
      containers:
      - name: my-deployment
        image: rohith221/proj2
        ports:
        - containerPort: 80
